### ISSUE TITLE
Script errors out at start with mafia r20242

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#31] opened 2020-07-08 11:36 UTC
`Function 'resetThisLoop( )' undefined. This script may require a more recent version of KoLmafia and/or its supporting scripts. (guzzlr.ash, line 609)`

This script worked yesterday with r20238.  Today I get the error cited above with r20238.  I'm going to assume that this is due to an overnight change in autoscend.

**Comment by taltamir** [comment] 2020-07-08 12:17
thank you for letting me know.
yes it was caused by a change in autoscend 5 hours ago.
fixed now in commit 0e8a0ed8e43dd1c5acebe928d571380adeb0997f
use `svn update` to get the fix

**Closed as completed by taltamir** 2020-07-08 12:17 UTC
