### ISSUE TITLE
Poop Deck access

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#23] opened 2020-06-07 11:19 UTC
Pirate fledges were in inventory and all zones were open.

`Visit to Island: The Poop Deck in progress...
You can't get to that area.

Failed to adventure in [The Poop Deck]
Stack trace:
  at guzzlr_deliverLoop (guzzlr.ash:688)
  at guzzlr_deliver (guzzlr.ash:706)
  at guzzlr_aftercore (guzzlr.ash:723)
  at main (guzzlr.ash:774)
printStackOnAbort => false
breakableHandling => 1
choiceAdventureScript => scripts\CounterChecker.ash
promptAboutCrafting => 1`

**Comment by taltamir** [comment] 2020-06-09 07:13
duplicate of #7

**Closed as completed by taltamir** 2020-06-09 07:13 UTC
